package com.sesoc.test.vo;

/**
 * ITR_FURNITURE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FurnitureVO {
	
	/** FURNITURE 번호. */
	private int furnitureNum;

	/** ITR_COMPANY 회사이름. */
	private String coNAME;

	/** FURNITURE 이름. */
	private String furnitureName;

	/** FURNITURE 종류. */
	private String type;

	/** FURNITURE 색상. */
	private String color;

	
	private String objPath;
	
	private String objTexture1;
	
	private String objTexture2;
	
	private String objTexture3;
	
	private String objTexture4;
	
	private String mtlPath;
	
	private String imgPath;

	public FurnitureVO(){}
	
	public FurnitureVO(int furnitureNum, String coNAME, String furnitureName, String type, String color, String objPath,
			String objTexture1, String objTexture2, String objTexture3, String objTexture4, String mtlPath,
			String imgPath) {
		super();
		this.furnitureNum = furnitureNum;
		this.coNAME = coNAME;
		this.furnitureName = furnitureName;
		this.type = type;
		this.color = color;
		this.objPath = objPath;
		this.objTexture1 = objTexture1;
		this.objTexture2 = objTexture2;
		this.objTexture3 = objTexture3;
		this.objTexture4 = objTexture4;
		this.mtlPath = mtlPath;
		this.imgPath = imgPath;
	}

	public int getFurnitureNum() {
		return furnitureNum;
	}

	public void setFurnitureNum(int furnitureNum) {
		this.furnitureNum = furnitureNum;
	}

	public String getCoNAME() {
		return coNAME;
	}

	public void setCoNAME(String coNAME) {
		this.coNAME = coNAME;
	}

	public String getFurnitureName() {
		return furnitureName;
	}

	public void setFurnitureName(String furnitureName) {
		this.furnitureName = furnitureName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getObjPath() {
		return objPath;
	}

	public void setObjPath(String objPath) {
		this.objPath = objPath;
	}

	public String getObjTexture1() {
		return objTexture1;
	}

	public void setObjTexture1(String objTexture1) {
		this.objTexture1 = objTexture1;
	}

	public String getObjTexture2() {
		return objTexture2;
	}

	public void setObjTexture2(String objTexture2) {
		this.objTexture2 = objTexture2;
	}

	public String getObjTexture3() {
		return objTexture3;
	}

	public void setObjTexture3(String objTexture3) {
		this.objTexture3 = objTexture3;
	}

	public String getObjTexture4() {
		return objTexture4;
	}

	public void setObjTexture4(String objTexture4) {
		this.objTexture4 = objTexture4;
	}

	public String getMtlPath() {
		return mtlPath;
	}

	public void setMtlPath(String mtlPath) {
		this.mtlPath = mtlPath;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}
	
	@Override
	public String toString() {
		return "FurnitureVO [furnitureNum=" + furnitureNum + ", coNAME=" + coNAME + ", furnitureName=" + furnitureName
				+ ", type=" + type + ", color=" + color + ", objPath=" + objPath + ", objTexture1=" + objTexture1
				+ ", objTexture2=" + objTexture2 + ", objTexture3=" + objTexture3 + ", objTexture4=" + objTexture4
				+ ", mtlPath=" + mtlPath + ", imgPath=" + imgPath + "]";
	}

}