package com.sesoc.test.vo;

/**
 * ITR_GALLERY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GalleryVO {

	/** GALLERY 번호. */
	private int galleryNum;

	/** ITR_USER 아이디. */
	private String id;

	/** IMG 서버에 저장되는 파일명. */
	private String imgUuid;

	/** GALLERY 제목. */
	private String title;

	/** GALLERY 내용. */
	private String content;

	/** GALLERY 작성 날짜. */
	private String inputdate;

	/** GALLERY 조회수. */
	private int hit;

	public GalleryVO() {
	}

	public GalleryVO(int galleryNum, String id, String imgUuid, String title, String content, String inputdate,
			int hit) {
		super();
		this.galleryNum = galleryNum;
		this.id = id;
		this.imgUuid = imgUuid;
		this.title = title;
		this.content = content;
		this.inputdate = inputdate;
		this.hit = hit;
	}

	public int getGalleryNum() {
		return galleryNum;
	}

	public void setGalleryNum(int galleryNum) {
		this.galleryNum = galleryNum;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getImgUuid() {
		return imgUuid;
	}

	public void setImgUuid(String imgUuid) {
		this.imgUuid = imgUuid;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getInputdate() {
		return inputdate;
	}

	public void setInputdate(String inputdate) {
		this.inputdate = inputdate;
	}

	public int getHit() {
		return hit;
	}

	public void setHit(int hit) {
		this.hit = hit;
	}
}