package com.sesoc.test.vo;

import java.util.Date;

/**
 * ITR_COMPANY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Graph4VO {

	/** COMPANY 가구수 */
	private int count;

	/** COMPANY 가구번호 */
	private String year;
	
	private String month;

	/** COMPANY 이미지번호 */
	private String company;

	public Graph4VO() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Graph4VO(int count, String year, String month, String company) {
		super();
		this.count = count;
		this.year = year;
		this.month = month;
		this.company = company;
	}

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Override
	public String toString() {
		return "Graph4VO [count=" + count + ", year=" + year + ", month=" + month + ", company=" + company + "]";
	}

	
	
	
	
}