package com.sesoc.test.vo;

import java.util.Date;

/**
 * ITR_COMPANY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Graph1VO {

	/** COMPANY 가구수 */
	private int count;

	/** COMPANY 가구번호 */
	private String year;

	/** COMPANY 이미지번호 */
	private String company;

	public Graph1VO() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Graph1VO(int count, String year, String company) {
		super();
		this.count = count;
		this.year = year;
		this.company = company;
	}

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Override
	public String toString() {
		return "Graph1VO [count=" + count + ", year=" + year + ", company=" + company + "]";
	}
	
	
	
}