package com.sesoc.test.vo;

/**
 * ITR_IMG 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ImgVO {

	/** IMG 서버에 저장되는 파일명. */
	private String imgUuid;

	/** USER 아이디. */
	private String id;

	/** IMG 저장 날짜. */
	private String savedDate;

	public ImgVO() {
		super();
		// TODO Auto-generated constructor stub
	}

	public String getImgUuid() {
		return imgUuid;
	}

	public void setImgUuid(String imgUuid) {
		this.imgUuid = imgUuid;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSavedDate() {
		return savedDate;
	}

	public void setSavedDate(String savedDate) {
		this.savedDate = savedDate;
	}

	public ImgVO(String imgUuid, String id, String savedDate) {
		super();
		this.imgUuid = imgUuid;
		this.id = id;
		this.savedDate = savedDate;
	}

	@Override
	public String toString() {
		return "ImgVO [imgUuid=" + imgUuid + ", id=" + id + ", savedDate=" + savedDate + "]";
	}

}