package com.sesoc.test.vo;

/**
 * ITR_MODEL 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ModelVO {

	/** MODEL 서버에 저장되는 파일명. */
	private String modelUuid;

	/** USER 아이디. */
	private String id;

	/** MODEL 이름. */
	private String modelName;

	/** MODEL 최초 제작 날짜. */
	private String createdate;

	/** MODEL 최근 수정 날짜. */
	private String modifydate;

	public ModelVO() {}

	public ModelVO(String modelUuid, String id, String modelName, String createdate, String modifydate) {
		super();
		this.modelUuid = modelUuid;
		this.id = id;
		this.modelName = modelName;
		this.createdate = createdate;
		this.modifydate = modifydate;
	}

	public String getModelUuid() {
		return modelUuid;
	}

	public void setModelUuid(String modelUuid) {
		this.modelUuid = modelUuid;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getModelName() {
		return modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public String getCreatedate() {
		return createdate;
	}

	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	public String getModifydate() {
		return modifydate;
	}

	public void setModifydate(String modifydate) {
		this.modifydate = modifydate;
	}

}