package com.sesoc.test.vo;

/**
 * ITR_COMPANY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RankVO {

	/** COMPANY 랭크 */
	private int rank;

	/** COMPANY 가구번호 */
	private int furnitureNum;

	/** COMPANY 이미지번호 */
	private String imgPath;
	
	/** USER 성별**/
	private String gender;

	/** USER 출생연도**/
	private String birthYear;

	public RankVO(){}
	
	public RankVO(int rank, int furnitureNum, String imgPath, String gender, String birthYear) {
		super();
		this.rank = rank;
		this.furnitureNum = furnitureNum;
		this.imgPath = imgPath;
		this.gender = gender;
		this.birthYear = birthYear;
	}
	
	public int getRank() {
		return rank;
	}
	
	public void setRank(int rank) {
		this.rank = rank;
	}
	
	public int getFurnitureNum() {
		return furnitureNum;
	}
	
	public void setFurnitureNum(int furnitureNum) {
		this.furnitureNum = furnitureNum;
	}
	
	public String getImgPath() {
		return imgPath;
	}
	
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}
	
	public String getGender() {
		return gender;
	}
	
	public void setGender(String gender) {
		this.gender = gender;
	}
	
	public String getBirthYear() {
		return birthYear;
	}
	
	public void setBirthYear(String birthYear) {
		this.birthYear = birthYear;
	}
	
	@Override
	public String toString() {
		return "RankVO [rank=" + rank + ", furnitureNum=" + furnitureNum + ", imgPath=" + imgPath + ", gender=" + gender
				+ ", birthYear=" + birthYear + "]";
	}
	
}