package com.sesoc.test.vo;

/**
 * ITR_COMPANY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class StatVO {
	
	/** COMPANY 가구번호 */
	private int furnitureNum;
	
	/** Furniture 이름**/
	private String FurnitureName;
	
	/** Company 타입 **/
	private String type;
	
	/** COMPANY 색상 */
	private String color;

	/** COMPANY 좋아요*/
	private String pick;

	public StatVO() {
		super();
	}
	
	public StatVO(int furnitureNum, String furnitureName, String type, String color, String pick) {
		super();
		this.furnitureNum = furnitureNum;
		FurnitureName = furnitureName;
		this.type = type;
		this.color = color;
		this.pick = pick;
	}

	public int getFurnitureNum() {
		return furnitureNum;
	}

	public void setFurnitureNum(int furnitureNum) {
		this.furnitureNum = furnitureNum;
	}

	public String getFurnitureName() {
		return FurnitureName;
	}

	public void setFurnitureName(String furnitureName) {
		FurnitureName = furnitureName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getPick() {
		return pick;
	}

	public void setPick(String pick) {
		this.pick = pick;
	}

	@Override
	public String toString() {
		return "StatVO [furnitureNum=" + furnitureNum + ", FurnitureName=" + FurnitureName + ", type=" + type
				+ ", color=" + color + ", pick=" + pick + "]";
	}
	
}