package com.sesoc.test.vo;

/**
 * ITR_USER 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserVO {

	/** USER 아이디. */
	private String id;

	/** USER 비밀번호. */
	private String pwd;

	/** USER 이름. */
	private String name;

	/** USER 이메일. */
	private String email;

	/** USER 성별. */
	private String gender;

	/** USER 생년월일. */
	private String birth;

	public UserVO() {
		super();
		// TODO Auto-generated constructor stub
	}

	public UserVO(String id, String pwd, String name, String email, String gender, String birth) {
		super();
		this.id = id;
		this.pwd = pwd;
		this.name = name;
		this.email = email;
		this.gender = gender;
		this.birth = birth;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getBirth() {
		return birth;
	}

	public void setBirth(String birth) {
		this.birth = birth;
	}

	@Override
	public String toString() {
		return "UserVO [id=" + id + ", pwd=" + pwd + ", name=" + name + ", email=" + email + ", gender=" + gender
				+ ", birth=" + birth + "]";
	}
	
}